backend/config/routes.rb
Backend::Application.routes.draw do
  resources :addresses
  resources :emails
  resources :contacts

end

backend/app/models/address.rb
class Address < ActiveRecord::Base
  attr_accessible :city, :contact_id, :contact, :state, :street_1, :street_2, :zip

  belongs_to :contact

  validates :street_1, :presence => true
  validates :state, :length => { :is => 2 }
end

backend/app/models/contact.rb
class Contact < ActiveRecord::Base

  # We need to add '_attributes' to be accessible so it can be set on the forms
  attr_accessible :dob, :first_name, :last_name, :emails, :emails_attributes, :addresses, :addresses_attributes, :_delete, :_destroy

  has_many :emails, :dependent => :destroy
  has_many :addresses, :dependent => :destroy

  accepts_nested_attributes_for :emails,    :allow_destroy => true, :reject_if => proc { |attributes| attributes['address'].blank? }
  accepts_nested_attributes_for :addresses, :allow_destroy => true, :reject_if => proc { |attributes| attributes['street_1'].blank? }

  validates :last_name, :presence => true
  validates :first_name, :presence => true

  validates_associated :emails, :addresses


end

backend/app/models/email.rb
class Email < ActiveRecord::Base
  attr_accessible :address, :contact_id, :contact

  belongs_to :contact

  validates :address, :presence => true

end

backend/app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @addresses }
    end
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
    @address = Address.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @address }
    end
  end

  # GET /addresses/new
  # GET /addresses/new.json
  def new
    @address = Address.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @address }
    end
  end

  # GET /addresses/1/edit
  def edit
    @address = Address.find(params[:id])
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(params[:address])

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render json: @address, status: :created, location: @address }
      else
        format.html { render action: "new" }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /addresses/1
  # PUT /addresses/1.json
  def update
    @address = Address.find(params[:id])

    respond_to do |format|
      if @address.update_attributes(params[:address])
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address = Address.find(params[:id])
    @address.destroy

    respond_to do |format|
      format.html { redirect_to addresses_url }
      format.json { head :no_content }
    end
  end
end

backend/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def sanitize_nested_params(params)
    # we strip off '0' from [{ '0' => { :id => '1', :foo => '234'}}]
    filter_params = params.select{ |k,v| k =~ /_attributes$/ }
    filter_params.each_pair do |k,v|
      filter_params[k] = v.map{ |x| x.values.first}
    end
    params.merge(filter_params)
  end

end

backend/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render_as_json_with_associations(@contacts) }
    end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @contact = Contact.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render_as_json_with_associations(@contact) }
    end
  end

  # GET /contacts/new
  # GET /contacts/new.json
  def new
    @contact = Contact.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render_as_json_with_associations(@contact) }
    end
  end

  # GET /contacts/1/edit
  #def edit
  #  @contact = Contact.find(params[:id])
  #end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(sanitize_params(params[:contact]))

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render json: @contact, status: :created, location: @contact }
      else
        format.html { render action: "new" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contacts/1
  # PUT /contacts/1.json
  def update
    @contact = Contact.find(params[:id])

    respond_to do |format|
      if @contact.update_attributes( sanitize_params(params[:contact]))
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url }
      format.json { head :no_content }
    end
  end

  private

  def render_as_json_with_associations(obj)
    render json: obj.to_json(:include => [:emails, :addresses], :except => [:updated_at, :created_at])
  end

  def sanitize_params(params)
    # drop anything we don't exepct because ActiveRecord doesn't like 'nil' for associations, blank is ok though
    params.delete(:addresses)
    params.delete(:emails)
    sanitize_nested_params(params)
  end

end

backend/app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  # GET /emails
  # GET /emails.json
  def index
    @emails = Email.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @emails }
    end
  end

  # GET /emails/1
  # GET /emails/1.json
  def show
    @email = Email.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @email }
    end
  end

  # GET /emails/new
  # GET /emails/new.json
  def new
    @email = Email.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @email }
    end
  end

  # GET /emails/1/edit
  def edit
    @email = Email.find(params[:id])
  end

  # POST /emails
  # POST /emails.json
  def create
    @email = Email.new(params[:email])

    respond_to do |format|
      if @email.save
        format.html { redirect_to @email, notice: 'Email was successfully created.' }
        format.json { render json: @email, status: :created, location: @email }
      else
        format.html { render action: "new" }
        format.json { render json: @email.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /emails/1
  # PUT /emails/1.json
  def update
    @email = Email.find(params[:id])

    respond_to do |format|
      if @email.update_attributes(params[:email])
        format.html { redirect_to @email, notice: 'Email was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @email.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emails/1
  # DELETE /emails/1.json
  def destroy
    @email = Email.find(params[:id])
    @email.destroy

    respond_to do |format|
      format.html { redirect_to emails_url }
      format.json { head :no_content }
    end
  end
end

backend/app/helpers/addresses_helper.rb
module AddressesHelper
end

backend/app/helpers/application_helper.rb
module ApplicationHelper
end

backend/app/helpers/contacts_helper.rb
module ContactsHelper
end

backend/app/helpers/emails_helper.rb
module EmailsHelper
end

backend/app/views/addresses/_form.html.erb
<%= form_for(@address) do |f| %>
  <% if @address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% @address.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :street_1 %><br />
    <%= f.text_field :street_1 %>
  </div>
  <div class="field">
    <%= f.label :street_2 %><br />
    <%= f.text_field :street_2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br />
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :contact %><br />
    <%= f.text_field :contact %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

backend/app/views/addresses/edit.html.erb
<h1>Editing address</h1>

<%= render 'form' %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

backend/app/views/addresses/index.html.erb
<h1>Listing addresses</h1>

<table>
  <tr>
    <th>Street 1</th>
    <th>Street 2</th>
    <th>City</th>
    <th>State</th>
    <th>Zip</th>
    <th>Contact</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @addresses.each do |address| %>
  <tr>
    <td><%= address.street_1 %></td>
    <td><%= address.street_2 %></td>
    <td><%= address.city %></td>
    <td><%= address.state %></td>
    <td><%= address.zip %></td>
    <td><%= address.contact %></td>
    <td><%= link_to 'Show', address %></td>
    <td><%= link_to 'Edit', edit_address_path(address) %></td>
    <td><%= link_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Address', new_address_path %>

backend/app/views/addresses/new.html.erb
<h1>New address</h1>

<%= render 'form' %>

<%= link_to 'Back', addresses_path %>

backend/app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Street 1:</b>
  <%= @address.street_1 %>
</p>

<p>
  <b>Street 2:</b>
  <%= @address.street_2 %>
</p>

<p>
  <b>City:</b>
  <%= @address.city %>
</p>

<p>
  <b>State:</b>
  <%= @address.state %>
</p>

<p>
  <b>Zip:</b>
  <%= @address.zip %>
</p>

<p>
  <b>Contact:</b>
  <%= @address.contact %>
</p>


<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>

backend/app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :dob %><br />
    <%= f.date_select :dob %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

backend/app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

backend/app/views/contacts/index.html.erb
<h1>Listing contacts</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Dob</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contacts.each do |contact| %>
  <tr>
    <td><%= contact.first_name %></td>
    <td><%= contact.last_name %></td>
    <td><%= contact.dob %></td>
    <td><%= link_to 'Show', contact %></td>
    <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
    <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Contact', new_contact_path %>

backend/app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

backend/app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @contact.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @contact.last_name %>
</p>

<p>
  <b>Dob:</b>
  <%= @contact.dob %>
</p>


<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

backend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Backend</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>